# Pandas Vectorization - Complete Guide

## What is Vectorization?

**Vectorization** is a technique in Pandas that allows you to perform operations on **an entire Series or DataFrame at once** instead of using loops (`for`, `while`) or functions like `apply()`.

Vectorized operations are **faster, cleaner, and more efficient** because they are built on top of **NumPy**, which is optimized for numerical computations.

---

# Why Use Vectorization?

Vectorization has many advantages:

- Faster execution
- Less code
- Easy to read
- Better performance on large datasets
- No need for loops in most cases

---

# Syntax

There is no special function called `vectorize()` in Pandas.

You simply perform operations directly on columns.

```python
df['column'] = df['column'] + 10
```

```python
df['new_column'] = df['column1'] + df['column2']
```

---

# Sample Dataset

```python
import pandas as pd

df = pd.DataFrame({
    'Name':['Ali','Sara','John','Ayesha'],
    'Age':[20,25,22,24],
    'Salary':[30000,45000,40000,50000]
})

df
```

| Name | Age | Salary |
|------|-----|--------|
| Ali | 20 | 30000 |
| Sara | 25 | 45000 |
| John | 22 | 40000 |
| Ayesha | 24 | 50000 |

---

# Arithmetic Operations

## Add a Number

```python
df['Age'] + 5
```

---

## Subtract

```python
df['Salary'] - 5000
```

---

## Multiply

```python
df['Salary'] * 2
```

---

## Divide

```python
df['Salary'] / 1000
```

---

## Modulus

```python
df['Age'] % 2
```

---

## Power

```python
df['Age'] ** 2
```

---

# Operations Between Columns

## Add Two Columns

```python
df['Total'] = df['Age'] + df['Salary']
```

---

## Subtract Columns

```python
df['Difference'] = df['Salary'] - df['Age']
```

---

## Multiply Columns

```python
df['Result'] = df['Age'] * df['Salary']
```

---

## Divide Columns

```python
df['Average'] = df['Salary'] / df['Age']
```

---

# Comparison Operations

## Greater Than

```python
df['Salary'] > 40000
```

---

## Less Than

```python
df['Age'] < 23
```

---

## Equal To

```python
df['Age'] == 20
```

---

## Not Equal To

```python
df['Age'] != 20
```

---

## Greater Than or Equal

```python
df['Salary'] >= 40000
```

---

## Less Than or Equal

```python
df['Salary'] <= 45000
```

---

# Boolean Operations

## AND

```python
(df['Age'] > 20) & (df['Salary'] > 35000)
```

---

## OR

```python
(df['Age'] > 22) | (df['Salary'] > 45000)
```

---

## NOT

```python
~(df['Age'] > 22)
```

---

# String Vectorization

Pandas provides the `.str` accessor for vectorized string operations.

## Convert to Uppercase

```python
df['Name'].str.upper()
```

---

## Convert to Lowercase

```python
df['Name'].str.lower()
```

---

## Title Case

```python
df['Name'].str.title()
```

---

## String Length

```python
df['Name'].str.len()
```

---

## Replace Text

```python
df['Name'].str.replace('Ali', 'Ahmed')
```

---

## Check Starts With

```python
df['Name'].str.startswith('A')
```

---

## Check Ends With

```python
df['Name'].str.endswith('a')
```

---

## Contains

```python
df['Name'].str.contains('a')
```

---

## Remove Spaces

```python
df['Name'].str.strip()
```

---

# Date and Time Vectorization

First convert the column into datetime.

```python
df['Date'] = pd.to_datetime(df['Date'])
```

## Get Year

```python
df['Date'].dt.year
```

---

## Get Month

```python
df['Date'].dt.month
```

---

## Get Day

```python
df['Date'].dt.day
```

---

## Get Day Name

```python
df['Date'].dt.day_name()
```

---

## Get Month Name

```python
df['Date'].dt.month_name()
```

---

# Mathematical Functions

## Absolute Value

```python
df['Salary'].abs()
```

---

## Round Values

```python
df['Salary'].round()
```

---

## Maximum

```python
df['Salary'].max()
```

---

## Minimum

```python
df['Salary'].min()
```

---

## Mean

```python
df['Salary'].mean()
```

---

## Sum

```python
df['Salary'].sum()
```

---

# Conditional Vectorization

## Using `where()`

```python
df['Salary'].where(df['Salary'] > 40000)
```

---

## Using `mask()`

```python
df['Salary'].mask(df['Salary'] > 40000)
```

---

## Using `np.where()`

```python
import numpy as np

df['Status'] = np.where(
    df['Salary'] > 40000,
    'High',
    'Low'
)
```

---

# Apply Functions to Entire Column

## Using `map()`

```python
df['Age'].map(lambda x: x + 1)
```

---

## Using `apply()`

```python
df['Salary'].apply(lambda x: x * 2)
```

> **Note:** `apply()` is useful, but true vectorized operations (like `df['Salary'] * 2`) are usually faster.

---

# Filtering Using Vectorization

```python
df[df['Salary'] > 40000]
```

---

```python
df[df['Age'] < 23]
```

---

```python
df[(df['Age'] > 20) & (df['Salary'] > 35000)]
```

---

# Creating New Columns

```python
df['Bonus'] = df['Salary'] * 0.10
```

---

```python
df['Tax'] = df['Salary'] * 0.05
```

---

```python
df['Net Salary'] = df['Salary'] - df['Tax']
```

---

# Common Vectorized Methods

| Method | Description |
|---------|-------------|
| `+` | Addition |
| `-` | Subtraction |
| `*` | Multiplication |
| `/` | Division |
| `%` | Modulus |
| `**` | Power |
| `.str` | String operations |
| `.dt` | Date and time operations |
| `.where()` | Keep values based on a condition |
| `.mask()` | Replace values based on a condition |
| `np.where()` | Create values using conditions |
| `.isin()` | Check if values exist in a list |
| `.between()` | Check if values are within a range |
| `.clip()` | Limit values to a range |

---

# Vectorization vs Loop

## Using Loop

```python
for i in df['Salary']:
    print(i * 2)
```

---

## Using Vectorization

```python
df['Salary'] * 2
```

Vectorization is shorter, faster, and recommended.

---

# Vectorization vs apply()

| Feature | Vectorization | apply() |
|---------|---------------|----------|
| Speed | Faster | Slower |
| Performance | High | Medium |
| Uses Loops | No | Internally Yes |
| Easy to Read | Yes | Yes |
| Best Choice | ✅ Yes | Only when needed |

---

# Advantages of Vectorization

- Very fast
- Uses optimized NumPy operations
- Less code
- Easy to understand
- Better performance for large datasets
- Reduces the need for loops
- Improves code readability

---

# Limitations

- Some complex row-wise operations cannot be fully vectorized.
- May use more memory for very large datasets.
- In some custom logic, `apply()` or loops may still be required.

---

# Real-World Uses

- Salary calculations
- Tax calculations
- Data cleaning
- Feature engineering
- String processing
- Date extraction
- Data transformation
- Machine learning preprocessing
- Financial analysis
- Business reporting

---

# Best Practices

- Prefer vectorized operations over loops.
- Avoid using `apply()` when a direct vectorized operation is available.
- Use `.str` for string columns.
- Use `.dt` for datetime columns.
- Use `np.where()` for conditional column creation.
- Use boolean indexing for filtering data.
- Take advantage of built-in Pandas and NumPy functions for better performance.

---

# Quick Revision

- Vectorization performs operations on an entire column at once.
- It is faster than loops.
- It is built on top of NumPy.
- Use direct column operations whenever possible.
- Use `.str` for string operations.
- Use `.dt` for datetime operations.
- Use `np.where()` for conditional logic.
- Use boolean indexing for filtering.

---

# Conclusion

**Vectorization** is one of the most important concepts in Pandas. It allows you to process entire columns efficiently without writing loops. It makes your code faster, cleaner, and easier to maintain. For most arithmetic, comparison, string, date, and conditional operations, vectorization is the recommended approach in Pandas.

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
# What are vetorized operation
a = np.array([1,2,3,4,5])
a * 2 # vectorized op

array([ 2,  4,  6,  8, 10])

In [ ]:
# problem in vectorized oprations in vanilla python
s = ['cat' , 'mat' , None,'rat']
[i.startswitch('c') for i in s]

AttributeError: 'str' object has no attribute 'startswitch'

In [ ]:
# How pandas solves this issue?

s = pd.Series(['cat','mat',None,'rat'])
# string accessor
s.str.startswith('c')
# fast and optimized

0     True
1    False
2    False
3    False
dtype: bool

In [ ]:
titan = pd.read_csv('titanic.csv')
titan['Name']

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: str

In [ ]:
# Common Functions
# lower/upper/capitalize/title
titan['Name'].str.lower()

0                                braund, mr. owen harris
1      cumings, mrs. john bradley (florence briggs th...
2                                 heikkinen, miss. laina
3           futrelle, mrs. jacques heath (lily may peel)
4                               allen, mr. william henry
                             ...
886                                montvila, rev. juozas
887                         graham, miss. margaret edith
888             johnston, miss. catherine helen "carrie"
889                                behr, mr. karl howell
890                                  dooley, mr. patrick
Name: Name, Length: 891, dtype: str

In [ ]:
titan['Name'].str.upper()

0                                BRAUND, MR. OWEN HARRIS
1      CUMINGS, MRS. JOHN BRADLEY (FLORENCE BRIGGS TH...
2                                 HEIKKINEN, MISS. LAINA
3           FUTRELLE, MRS. JACQUES HEATH (LILY MAY PEEL)
4                               ALLEN, MR. WILLIAM HENRY
                             ...
886                                MONTVILA, REV. JUOZAS
887                         GRAHAM, MISS. MARGARET EDITH
888             JOHNSTON, MISS. CATHERINE HELEN "CARRIE"
889                                BEHR, MR. KARL HOWELL
890                                  DOOLEY, MR. PATRICK
Name: Name, Length: 891, dtype: str

In [ ]:
titan['Name'].str.capitalize()

0                                Braund, mr. owen harris
1      Cumings, mrs. john bradley (florence briggs th...
2                                 Heikkinen, miss. laina
3           Futrelle, mrs. jacques heath (lily may peel)
4                               Allen, mr. william henry
                             ...
886                                Montvila, rev. juozas
887                         Graham, miss. margaret edith
888             Johnston, miss. catherine helen "carrie"
889                                Behr, mr. karl howell
890                                  Dooley, mr. patrick
Name: Name, Length: 891, dtype: str

In [ ]:
titan['Name'].str.title()

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: str

In [ ]:
# len

titan['Name'].str.len() == 82

0      False
1      False
2      False
3      False
4      False
       ...
886    False
887    False
888    False
889    False
890    False
Name: Name, Length: 891, dtype: bool

In [ ]:
titan['Name'][titan['Name'].str.len() == 82].values[0]

'Penasco y Castellana, Mrs. Victor de Satode (Maria Josefa Perez de Soto y Vallejo)'

In [ ]:
#strip Remove all the leading or tliding zerors

'                Zain       '.strip()
titan['Name'].str.strip()

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: str

In [ ]:
# split-> get
titan['Last_name'] =titan['Name'].str.split(',').str.get(0) # get is use to extract from list

In [ ]:
titan['Name'].str.split(',').str.get(1).str.split('.').str.get(0)

0         Mr
1        Mrs
2       Miss
3        Mrs
4         Mr
       ...
886      Rev
887     Miss
888     Miss
889       Mr
890       Mr
Name: Name, Length: 891, dtype: object

In [ ]:
titan[['title','first_name']] = titan['Name'].str.split(',').str.get(1).str.strip().str.split(' ', n = 1,expand=True )
titan.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Last_name,title,first_name
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,Braund,Mr.,Owen Harris
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,Cumings,Mrs.,John Bradley (Florence Briggs Thayer)
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,Heikkinen,Miss.,Laina
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,Futrelle,Mrs.,Jacques Heath (Lily May Peel)
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,Allen,Mr.,William Henry

In [ ]:
# how many miss and mr

titan['title'].value_counts()

title
Mr.          517
Miss.        182
Mrs.         125
Master.       40
Dr.            7
Rev.           6
Major.         2
Mlle.          2
Col.           2
Don.           1
Mme.           1
Ms.            1
Lady.          1
Sir.           1
Capt.          1
the            1
Jonkheer.      1
Name: count, dtype: int64

In [ ]:
titan['Name'].str.split('.').str.get(1)

0                                 Owen Harris
1       John Bradley (Florence Briggs Thayer)
2                                       Laina
3               Jacques Heath (Lily May Peel)
4                               William Henry
                        ...
886                                    Juozas
887                            Margaret Edith
888                  Catherine Helen "Carrie"
889                               Karl Howell
890                                   Patrick
Name: Name, Length: 891, dtype: object

In [ ]:
# Replace
titan ['title'] = titan['title'].str.replace('Ms','Miss')
titan['title'] = titan['title'].str.replace('Mlle','Miss')

In [ ]:
# how many miss and mr

titan['title'].value_counts()

title
Mr.          517
Miss.        185
Mrs.         125
Master.       40
Dr.            7
Rev.           6
Major.         2
Col.           2
Don.           1
Mme.           1
Lady.          1
Sir.           1
Capt.          1
the            1
Jonkheer.      1
Name: count, dtype: int64

In [ ]:
# filtering
# startswith/endswith

titan[titan['first_name'].str.startswith('A')]
titan[titan['first_name'].str.endswith('A')]
# isdigit/isalpha...
titan[titan['first_name'].str.isdigit()] # no passenger

Empty DataFrame
Columns: [PassengerId, Survived, Pclass, Name, Sex, Age, SibSp, Parch, Ticket, Fare, Cabin, Embarked, Last_name, title, first_name]
Index: []

In [ ]:
# applying regex
# contains
# search john -> both case

titan[titan['first_name'].str.contains('john',case=False)]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Last_name,title,first_name
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,Cumings,Mrs.,John Bradley (Florence Briggs Thayer)
41,42,0,2,"Turpin, Mrs. William John Robert (Dorothy Ann ...",female,27.0,1,0,11668,21.0000,NaN,S,Turpin,Mrs.,William John Robert (Dorothy Ann Wonnacott)
45,46,0,3,"Rogers, Mr. William John",male,NaN,0,0,S.C./A.4. 23567,8.0500,NaN,S,Rogers,Mr.,William John
98,99,1,2,"Doling, Mrs. John T (Ada Julia Bone)",female,34.0,0,1,231919,23.0000,NaN,S,Doling,Mrs.,John T (Ada Julia Bone)
112,113,0,3,"Barton, Mr. David John",male,22.0,0,0,324669,8.0500,NaN,S,Barton,Mr.,David John
117,118,0,2,"Turpin, Mr. William John Robert",male,29.0,1,0,11668,21.0000,NaN,S,Turpin,Mr.,William John Robert
160,161,0,3,"Cribb, Mr. John Hatfield",male,44.0,0,1,371362,16.1000,NaN,S,Cribb,Mr.,John Hatfield
162,163,0,3,"Bengtsson, Mr. John Viktor",male,26.0,0,0,347068,7.7750,NaN,S,Bengtsson,Mr.,John Viktor
165,166,1,3,"Goldsmith, Master. Frank John William ""Frankie""",male,9.0,0,2,363291,20.5250,NaN,S,Goldsmith,Master.,"Frank John William ""Frankie"""
168,169,0,1,"Baumann, Mr. John D",male,NaN,0,0,PC 17318,25.9250,NaN,S,Baumann,Mr.,John D
188,189,0,3,"Bourke, Mr. John",male,40.0,1,1,364849,15.5000,NaN,Q,Bourke,Mr.,John
212,213,0,3,"Perkin, Mr. John Henry",male,22.0,0,0,A/5 21174,7.2500,NaN,S,Perkin,Mr.,John Henry
226,227,1,2,"Mellors, Mr. William John",male,19.0,0,0,SW/PP 751,10.5000,NaN,S,Mellors,Mr.,William John
227,228,0,3,"Lovell, Mr. John Hall (""Henry"")",male,20.5,0,0,A/5 21173,7.2500,NaN,S,Lovell,Mr.,"John Hall (""Henry"")"
324,325,0,3,"Sage, Mr. George John Jr",male,NaN,8,2,CA. 2343,69.5500,NaN,S,Sage,Mr.,George John Jr
328,329,1,3,"Goldsmith, Mrs. Frank John (Emily Alice Brown)",female,31.0,1,1,363291,20.5250,NaN,S,Goldsmith,Mrs.,Frank John (Emily Alice Brown)
401,402,0,3,"Adams, Mr. John",male,26.0,0,0,341826,8.0500,NaN,S,Adams,Mr.,John
418,419,0,2,"Matthews, Mr. William John",male,30.0,0,0,28228,13.0000,NaN,S,Matthews,Mr.,William John
467,468,0,1,"Smart, Mr. John Montgomery",male,56.0,0,0,113792,26.5500,NaN,S,Smart,Mr.,John Montgomery
527,528,0,1,"Farthing, Mr. John",male,NaN,0,0,PC 17483,221.7792,C95,S,Farthing,Mr.,John
548,549,0,3,"Goldsmith, Mr. Frank John",male,33.0,1,1,363291,20.5250,NaN,S,Goldsmith,Mr.,Frank John
549,550,1,2,"Davies, Master. John Morgan Jr",male,8.0,1,1,C.A. 33112,36.7500,NaN,S,Davies,Master.,John Morgan Jr
550,551,1,1,"Thayer, Mr. John Borland Jr",male,17.0,0,2,17421,110.8833,C70,C,Thayer,Mr.,John Borland Jr
563,564,0,3,"Simmons, Mr. John",male,NaN,0,0,SOTON/OQ 392082,8.0500,NaN,S,Simmons,Mr.,John
572,573,1,1,"Flynn, Mr. John Irwin (""Irving"")",male,36.0,0,0,PC 17474,26.3875,E25,S,Flynn,Mr.,"John Irwin (""Irving"")"
574,575,0,3,"Rush, Mr. Alfred George John",male,16.0,0,0,A/4. 20589,8.0500,NaN,S,Rush,Mr.,Alfred George John
581,582,1,1,"Thayer, Mrs. John Borland (Marian Longstreth M...",female,39.0,1,1,17421,110.8833,C68,C,Thayer,Mrs.,John Borland (Marian Longstreth Morris)
583,584,0,1,"Ross, Mr. John Hugo",male,36.0,0,0,13049,40.1250,A10,C,Ross,Mr.,John Hugo
586,587,0,2,"Jarvis, Mr. John Denzil",male,47.0,0,0,237565,15.0000,NaN,S,Jarvis,Mr.,John Denzil
594,595,0,2,"Chapman, Mr. John Henry",male,37.0,1,0,SC/AH 29037,26.0000,NaN,S,Chapman,Mr.,John Henry
613,614,0,3,"Horgan, Mr. John",male,NaN,0,0,370377,7.7500,NaN,Q,Horgan,Mr.,John
624,625,0,3,"Bowen, Mr. David John ""Dai""",male,21.0,0,0,54636,16.1000,NaN,S,Bowen,Mr.,"David John ""Dai"""
657,658,0,3,"Bourke, Mrs. John (Catherine)",female,32.0,1,1,364849,15.5000,NaN,Q,Bourke,Mrs.,John (Catherine)
694,695,0,1,"Weir, Col. John",male,60.0,0,0,113800,26.5500,NaN,S,Weir,Col.,John
698,699,0,1,"Thayer, Mr. John Borland",male,49.0,1,1,17421,110.8833,C68,C,Thayer,Mr.,John Borland
700,701,1,1,"Astor, Mrs. John Jacob (Madeleine Talmadge Force)",female,18.0,1,0,PC 17757,227.5250,C62 C64,C,Astor,Mrs.,John Jacob (Madeleine Talmadge Force)
733,734,0,2,"Berriman, Mr. William John",male,23.0,0,0,28425,13.0000,NaN,S,Berriman,Mr.,William John
760,761,0,3,"Garfirth, Mr. John",male,NaN,0,0,358585,14.5000,NaN,S,Garfirth,Mr.,John
765,766,1,1,"Hogeboom, Mrs. John C (Anna Andrews)",female,51.0,1,0,13502,77.9583,D11,S,Hogeboom,Mrs.,John C (Anna Andrews)
818,819,0,3,"Holm, Mr. John Fredrik Alexander",male,43.0,0,0,C 7075,6.4500,NaN,S,Holm,Mr.,John Fredrik Alexander
822,823,0,1,"Reuchlin, Jonkheer. John George",male,38.0,0,0,19972,0.0000,NaN,S,Reuchlin,Jonkheer.,John George
825,826,0,3,"Flynn, Mr. John",male,NaN,0,0,368323,6.9500,NaN,Q,Flynn,Mr.,John
848,849,0,2,"Harper, Rev. John",male,28.0,0,1,248727,33.0000,NaN,S,Harper,Rev.,John
864,865,0,2,"Gill, Mr. John William",male,24.0,0,0,233866,13.0000,NaN,S,Gill,Mr.,John William

In [ ]:
# find lastnames with start and end char vowel

titan[titan['Last_name'].str.contains('^[aeiouAEIOU].+[aeiouAEIOU]$')]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Last_name,title,first_name
30,31,0,1,"Uruchurtu, Don. Manuel E",male,40.0,0,0,PC 17601,27.7208,NaN,C,Uruchurtu,Don.,Manuel E
49,50,0,3,"Arnold-Franchi, Mrs. Josef (Josefine Franchi)",female,18.0,1,0,349237,17.8000,NaN,S,Arnold-Franchi,Mrs.,Josef (Josefine Franchi)
207,208,1,3,"Albimona, Mr. Nassef Cassem",male,26.0,0,0,2699,18.7875,NaN,C,Albimona,Mr.,Nassef Cassem
210,211,0,3,"Ali, Mr. Ahmed",male,24.0,0,0,SOTON/O.Q. 3101311,7.0500,NaN,S,Ali,Mr.,Ahmed
353,354,0,3,"Arnold-Franchi, Mr. Josef",male,25.0,1,0,349237,17.8000,NaN,S,Arnold-Franchi,Mr.,Josef
493,494,0,1,"Artagaveytia, Mr. Ramon",male,71.0,0,0,PC 17609,49.5042,NaN,C,Artagaveytia,Mr.,Ramon
518,519,1,2,"Angle, Mrs. William A (Florence ""Mary"" Agnes H...",female,36.0,1,0,226875,26.0000,NaN,S,Angle,Mrs.,"William A (Florence ""Mary"" Agnes Hughes)"
784,785,0,3,"Ali, Mr. William",male,25.0,0,0,SOTON/O.Q. 3101312,7.0500,NaN,S,Ali,Mr.,William
840,841,0,3,"Alhomaki, Mr. Ilmari Rudolf",male,20.0,0,0,SOTON/O2 3101287,7.9250,NaN,S,Alhomaki,Mr.,Ilmari Rudolf

In [ ]:

titan[titan['Last_name'].str.contains('^[^aeiouAEIOU].+[^aeiouAEIOU]$')] # not aeiou

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Last_name,title,first_name
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,Braund,Mr.,Owen Harris
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,Cumings,Mrs.,John Bradley (Florence Briggs Thayer)
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,Heikkinen,Miss.,Laina
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q,Moran,Mr.,James
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S,McCarthy,Mr.,Timothy J
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
884,885,0,3,"Sutehall, Mr. Henry Jr",male,25.0,0,0,SOTON/OQ 392076,7.0500,NaN,S,Sutehall,Mr.,Henry Jr
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,Graham,Miss.,Margaret Edith
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,Johnston,Miss.,"Catherine Helen ""Carrie"""
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,Behr,Mr.,Karl Howell
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,Dooley,Mr.,Patrick

In [ ]:
# slicing
titan['Name'].str[:4]

0      Brau
1      Cumi
2      Heik
3      Futr
4      Alle
       ...
886    Mont
887    Grah
888    John
889    Behr
890    Dool
Name: Name, Length: 891, dtype: str

In [ ]:
titan['Name'].str[::2]

0                    Ban,M.Oe ars
1      Cmns r.Jh rde Foec rgsTae)
2                     Hiknn is an
3          Ftel,Ms aqe et Ll a el
4                    Aln r ila er
                  ...
886                   Mnvl,Rv uzs
887                Gaa,Ms.Mrae dt
888          Jhso,Ms.CteieHln"are
889                   Bh,M.Kr oel
890                    Doe,M.Ptik
Name: Name, Length: 891, dtype: str

In [ ]:
titan['Name'].str[::-1] # reverse the name

0                                sirraH newO .rM ,dnuarB
1      )reyahT sggirB ecnerolF( yeldarB nhoJ .srM ,sg...
2                                 aniaL .ssiM ,nenikkieH
3           )leeP yaM yliL( htaeH seuqcaJ .srM ,ellertuF
4                               yrneH mailliW .rM ,nellA
                             ...
886                                sazouJ .veR ,alivtnoM
887                         htidE teragraM .ssiM ,maharG
888             "eirraC" neleH enirehtaC .ssiM ,notsnhoJ
889                                llewoH lraK .rM ,rheB
890                                  kcirtaP .rM ,yelooD
Name: Name, Length: 891, dtype: str